# -*- coding: utf-8 -*-
"""新版(全產業)_xy軸變數比對.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CUpg3n0weVdtOl4ukxW71uAK8VFiLGWQ

總檔
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

# *** 設定變數 ***
# Data
input_data = pd.read_excel(r"/content/drive/MyDrive/data_MS/資料總檔/新財務變數/KS模型/excel/統整檔案(已估計)_0920更新.xlsx",keep_default_na=False)

# Path
output_path ="/content/drive/MyDrive/data_MS/資料總檔/新財務變數/KS模型/excel/統整檔案(貼上變數)_0920更新.xlsx"

# Variable
variable_name = 'knowledge utilization partner1'
start_year = 1992



"""硬體

"""

variable_data = pd.read_excel(r"/content/drive/MyDrive/data_MS/xy軸_變數比對/knowledge utilization partner變數/Hardware_KnowledgeUtilizationPartner.xlsx", sheet_name='Knowledge Utilization Partner 1', header=0,na_values='#N/A',keep_default_na=False)

# cusip-6成cusip6
variable_data = variable_data.rename(columns={'cusip-6':'cusip6'})

# 比對檔案cusip檢查
# 硬體比對檔案沒有cusip，因此使用company編號做比對，且以純數字做比對
for c in range(len(variable_data)):
  variable_data.loc[c,'cusip6'] =variable_data['cusip6'][c].strip("C")
  variable_data.loc[c,'cusip6'] =variable_data['cusip6'][c].strip("0")

# 將cusip轉成int
variable_data["cusip6"]= variable_data["cusip6"].astype(int)

# year
for y in range(25):
  variable_data = variable_data.rename(columns={start_year+y: str(start_year+y)+'y'})

# *** 變數 ***
for i in range(5191,6853):
  cusip = str(input_data["Company"][i])
  year = input_data["Year"][i]
  header_year = str(year)+'y'
  # 去除company的0
  cusip = cusip.strip("0")
  cusip = int(cusip)
  #如果年份不再1992-2016，則不做
  if year<1992 or year>2016:
    input_data[variable_name][i] = '#N/A'
    pass
  else:
    try:
      print(cusip,year)
      dataframe_cusip = variable_data[variable_data["cusip6"] == cusip]
      dataframe_cusip = dataframe_cusip.reset_index(drop=True)
      value = dataframe_cusip[header_year][0]
      print(value)
      input_data.loc[i,variable_name] = value
    except:
      print("ERROR")
      input_data.loc[i,variable_name] = '#N/A'
      pass

"""軟體

"""

variable_data = pd.read_excel(r"/content/drive/MyDrive/data_MS/xy軸_變數比對/knowledge utilization partner變數/軟體KUP.xlsx", sheet_name='KUP1', header=0,na_values='#N/A',keep_default_na=False)

# cusip-6成cusip6
variable_data = variable_data.rename(columns={'cusip-6':'cusip6'})

# 比對檔案cusip檢查
# 如果比對檔案之cusip前面的0不見了，則補0
for c in range(len(variable_data)):
  check_variable_cusip = str(variable_data["cusip6"][c])
  if len(check_variable_cusip)<6:
    loss = 6 - len(check_variable_cusip)
    zero = '0'*loss
    check_variable_cusip = zero + check_variable_cusip
    variable_data.loc[c,'cusip6'] = check_variable_cusip

# 將cusip轉成str
variable_data["cusip6"]= variable_data["cusip6"].astype(str)

# year
for y in range(25):
  variable_data = variable_data.rename(columns={start_year+y: str(start_year+y)+'y'})

# *** 變數 ***
for i in range(6853,8531):
  cusip = str(input_data["cusip-6"][i])
  year = input_data["Year"][i]
  header_year = str(year)+'y'
  #如果cusip前面的0不見了，則補0
  if len(cusip)<6:
    loss = 6 - len(cusip)
    zero = '0'*loss
    cusip = zero+cusip
  #如果年份不再1992-2016，則不做
  if year<1992 or year>2016:
    input_data[variable_name][i] = '#N/A'
    pass
  else:
    try:
      print(cusip,year)
      dataframe_cusip = variable_data[variable_data["cusip6"] == cusip]
      dataframe_cusip = dataframe_cusip.reset_index(drop=True)
      value = dataframe_cusip[header_year][0]
      print(value)
      input_data[variable_name][i] = value
    except:
      print("ERROR")
      input_data[variable_name][i] = '#N/A'
      pass

"""電信"""

variable_data = pd.read_excel(r"/content/drive/MyDrive/data_MS/xy軸_變數比對/knowledge utilization partner變數/Telecom_KnowledgeUtilizationPartner.xlsx", sheet_name='Knowledge Utilization Partner 1', header=0,na_values='#N/A',keep_default_na=False)

# cusip-6成cusip6
variable_data = variable_data.rename(columns={'cusip-6':'cusip6'})

# 比對檔案cusip檢查
# 如果比對檔案之cusip前面的0不見了，則補0
for c in range(len(variable_data)):
  check_variable_cusip = str(variable_data["cusip6"][c])
  if len(check_variable_cusip)<6:
    loss = 6 - len(check_variable_cusip)
    zero = '0'*loss
    check_variable_cusip = zero + check_variable_cusip
    variable_data.loc[c,'cusip6'] = check_variable_cusip

# 將cusip轉成str
variable_data["cusip6"]= variable_data["cusip6"].astype(str)

# year
for y in range(25):
  variable_data = variable_data.rename(columns={start_year+y: str(start_year+y)+'y'})

# *** 變數 ***
for i in range(8531,17784):
  cusip = str(input_data["cusip-6"][i])
  year = input_data["Year"][i]
  header_year = str(year)+'y'
  #如果cusip前面的0不見了，則補0
  if len(cusip)<6:
    loss = 6 - len(cusip)
    zero = '0'*loss
    cusip = zero+cusip
  #如果年份不再1992-2016，則不做
  if year<1992 or year>2016:
    input_data[variable_name][i] = '#N/A'
    pass
  else:
    try:
      print(cusip,year)
      dataframe_cusip = variable_data[variable_data["cusip6"] == cusip]
      dataframe_cusip = dataframe_cusip.reset_index(drop=True)
      value = dataframe_cusip[header_year][0]
      print(value)
      input_data[variable_name][i] = value
    except:
      print("ERROR")
      input_data[variable_name][i] = '#N/A'
      pass

"""半導體"""

variable_data = pd.read_excel(r"/content/drive/MyDrive/data_MS/xy軸_變數比對/knowledge utilization partner變數/Semicon_KnowledgeUtilizationPartner.xlsx", sheet_name='KUP1', header=0,na_values='#N/A',keep_default_na=False)

# cusip-6成cusip6
variable_data = variable_data.rename(columns={'cusip-6':'cusip6'})

# 比對檔案cusip檢查
# 如果比對檔案之cusip前面的0不見了，則補0
for c in range(len(variable_data)):
  check_variable_cusip = str(variable_data["cusip6"][c])
  if len(check_variable_cusip)<6:
    loss = 6 - len(check_variable_cusip)
    zero = '0'*loss
    check_variable_cusip = zero + check_variable_cusip
    variable_data.loc[c,'cusip6'] = check_variable_cusip

# 將cusip轉成str
variable_data["cusip6"]= variable_data["cusip6"].astype(str)

# year
for y in range(25):
  variable_data = variable_data.rename(columns={start_year+y: str(start_year+y)+'y'})

# *** 變數 ***
for i in range(1555,5191):
  cusip = str(input_data["cusip-6"][i])
  year = input_data["Year"][i]
  header_year = str(year)+'y'
  #如果cusip前面的0不見了，則補0
  if len(cusip)<6:
    loss = 6 - len(cusip)
    zero = '0'*loss
    cusip = zero+cusip
  #如果年份不再1992-2016，則不做
  if year<1992 or year>2016:
    input_data[variable_name][i] = '#N/A'
    pass
  else:
    try:
      print(cusip,year)
      dataframe_cusip = variable_data[variable_data["cusip6"] == cusip]
      dataframe_cusip = dataframe_cusip.reset_index(drop=True)
      value = dataframe_cusip[header_year][0]
      print(value)
      input_data[variable_name][i] = value
    except:
      print("ERROR")
      input_data[variable_name][i] = '#N/A'
      pass

"""生醫"""

variable_data = pd.read_excel(r"/content/drive/MyDrive/data_MS/xy軸_變數比對/knowledge utilization partner變數/BioPhar_KnowledgeUtilizationPartner.xlsx", sheet_name='KUP1', header=0,na_values='#N/A',keep_default_na=False)

# cusip-6成cusip6
variable_data = variable_data.rename(columns={'cusip-6':'cusip6'})

# 比對檔案cusip檢查
# 如果比對檔案之cusip前面的0不見了，則補0
for c in range(len(variable_data)):
  check_variable_cusip = str(variable_data["cusip6"][c])
  if len(check_variable_cusip)<6:
    loss = 6 - len(check_variable_cusip)
    zero = '0'*loss
    check_variable_cusip = zero + check_variable_cusip
    variable_data.loc[c,'cusip6'] = check_variable_cusip

# 將cusip轉成str
variable_data["cusip6"]= variable_data["cusip6"].astype(str)

# year
for y in range(25):
  variable_data = variable_data.rename(columns={start_year+y: str(start_year+y)+'y'})

# *** 變數 ***
for i in range(1556):
  cusip = str(input_data["cusip-6"][i])
  year = input_data["Year"][i]
  header_year = str(year)+'y'
  #如果cusip前面的0不見了，則補0
  if len(cusip)<6:
    loss = 6 - len(cusip)
    zero = '0'*loss
    cusip = zero+cusip
  #如果年份不再1992-2016，則不做
  if year<1992 or year>2016:
    input_data[variable_name][i] = '#N/A'
    pass
  else:
    try:
      print(cusip,year)
      dataframe_cusip = variable_data[variable_data["cusip6"] == cusip]
      dataframe_cusip = dataframe_cusip.reset_index(drop=True)
      value = dataframe_cusip[header_year][0]
      print(value)
      input_data[variable_name][i] = value
    except:
      print("ERROR")
      input_data[variable_name][i] = '#N/A'
      pass

"""輸出檔案


"""

input_data.to_excel(output_path,index=False)

